// This file will be auto-generated by `npm run supabase:gen-types`
// For now, we define the types manually based on our schema

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          email: string;
          tier: 'free' | 'pro';
          storage_used_bytes: number;
          storage_limit_bytes: number;
          free_message_used: boolean;
          stripe_customer_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          email: string;
          tier?: 'free' | 'pro';
          storage_used_bytes?: number;
          storage_limit_bytes?: number;
          free_message_used?: boolean;
          stripe_customer_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          email?: string;
          tier?: 'free' | 'pro';
          storage_used_bytes?: number;
          storage_limit_bytes?: number;
          free_message_used?: boolean;
          stripe_customer_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      messages: {
        Row: {
          id: string;
          user_id: string;
          message_text: string;
          video_storage_path: string | null;
          video_size_bytes: number;
          video_duration_seconds: number;
          delivery_email: string;
          scheduled_date: string;
          status: 'pending' | 'delivered' | 'failed';
          delivery_token: string;
          delivered_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          message_text: string;
          video_storage_path?: string | null;
          video_size_bytes?: number;
          video_duration_seconds?: number;
          delivery_email: string;
          scheduled_date: string;
          status?: 'pending' | 'delivered' | 'failed';
          delivery_token?: string;
          delivered_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          message_text?: string;
          video_storage_path?: string | null;
          video_size_bytes?: number;
          video_duration_seconds?: number;
          delivery_email?: string;
          scheduled_date?: string;
          status?: 'pending' | 'delivered' | 'failed';
          delivery_token?: string;
          delivered_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'messages_user_id_fkey';
            columns: ['user_id'];
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          }
        ];
      };
      payments: {
        Row: {
          id: string;
          user_id: string | null;
          stripe_payment_intent_id: string;
          stripe_checkout_session_id: string | null;
          amount_cents: number;
          currency: string;
          product_type: 'pro_upgrade' | 'storage_addon';
          storage_bytes_added: number;
          status: 'pending' | 'completed' | 'failed' | 'refunded';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          stripe_payment_intent_id: string;
          stripe_checkout_session_id?: string | null;
          amount_cents: number;
          currency?: string;
          product_type: 'pro_upgrade' | 'storage_addon';
          storage_bytes_added?: number;
          status?: 'pending' | 'completed' | 'failed' | 'refunded';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          stripe_payment_intent_id?: string;
          stripe_checkout_session_id?: string | null;
          amount_cents?: number;
          currency?: string;
          product_type?: 'pro_upgrade' | 'storage_addon';
          storage_bytes_added?: number;
          status?: 'pending' | 'completed' | 'failed' | 'refunded';
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'payments_user_id_fkey';
            columns: ['user_id'];
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          }
        ];
      };
      delivery_logs: {
        Row: {
          id: string;
          message_id: string;
          attempt_number: number;
          status: 'pending' | 'delivered' | 'sent' | 'bounced' | 'failed';
          email_provider_id: string | null;
          error_message: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          message_id: string;
          attempt_number?: number;
          status: 'pending' | 'delivered' | 'sent' | 'bounced' | 'failed';
          email_provider_id?: string | null;
          error_message?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          message_id?: string;
          attempt_number?: number;
          status?: 'pending' | 'delivered' | 'sent' | 'bounced' | 'failed';
          email_provider_id?: string | null;
          error_message?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'delivery_logs_message_id_fkey';
            columns: ['message_id'];
            referencedRelation: 'messages';
            referencedColumns: ['id'];
          }
        ];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      update_storage_used: {
        Args: {
          p_user_id: string;
          p_delta_bytes: number;
        };
        Returns: undefined;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
}

export type Profile = Database['public']['Tables']['profiles']['Row'];
export type Message = Database['public']['Tables']['messages']['Row'];
export type Payment = Database['public']['Tables']['payments']['Row'];
export type DeliveryLog = Database['public']['Tables']['delivery_logs']['Row'];
